version: '3.4'
services:
  mongodb:
    image: mongo
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
